### ISSUE TITLE
Early weapon setting

### ISSUE THREAD

**Issue by Chris-Is-Awesome** [Extra-2-Dew/ArchipelagoRandomizer#19]
Add a setting to allow choosing which weapon will be your first logical one. This can spice up seeds by more often forcing you to not have stick as first weapon.

**Comment by GameWyrm** [comment]
Should be easy enough. The way I'll do this is to have an option in the YAML like so:
```yaml
early_weapon_choice:
  option_off: 50
  option_melee: 0
  option_force_wand: 0
  option_dynamite: 0
  option_ice_ring: 0
```
You can use a combination of choices to have the early weapon be random; for example you could set force, dynamite, and ice to 50 and the other choices to 0 to make it unlikely you'd get a stick early.
